const images_url = [
    {
        name:'aot',
        image:'assets/aot.jpg'
    },
    {
        name:'aot',
        image:'assets/aot.jpg'
    },
    {
        name:'akatsuki',
        image:'assets/akatsuki.jpg'
    },
    {
        name:'akatsuki',
        image:'assets/akatsuki.jpg'
    },
    {
        name:'black',
        image:'assets/black.jpg'
    },
    {
        name:'black',
        image:'assets/black.jpg'
    },
    {
        name:'boule',
        image:'assets/boule.jpg'
    },
    {
        name:'boule',
        image:'assets/boule.jpg'
    },
    {
        name:'fairy',
        image:'assets/fairy.jpg'
    },
    {
        name:'fairy',
        image:'assets/fairy.jpg'
    },
    {
        name:'konoha',
        image:'assets/konoha.jpg'
    },
    {
        name:'konoha',
        image:'assets/konoha.jpg'
    },
    {
        name:'l',
        image:'assets/l.jpg'
    },
    {
        name:'l',
        image:'assets/l.jpg'
    },
    {
        name:'piece',
        image:'assets/piece.jpg'
    },
    {
        name:'piece',
        image:'assets/piece.jpg'
    },
    {
        name:'uchiha',
        image:'assets/uchiha.jpg'
    },
    {
        name:'uchiha',
        image:'assets/uchiha.jpg'
    },
]